-- SQL SERVER

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%nome_da_coluna%'
ORDER BY TABLE_NAME;

-- ORACLE

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%nome_da_coluna%'
ORDER BY TABLE_NAME;
