SELECT 
    CASE
      WHEN LS.ID_EMPRESA = '11' THEN '11'
      WHEN LS.ID_EMPRESA = '10' THEN '10'
      WHEN LS.ID_EMPRESA = '009' THEN '9'
      WHEN LS.ID_EMPRESA = '008' THEN '8'
      WHEN LS.ID_EMPRESA = '007' THEN '7'
      WHEN LS.ID_EMPRESA = '004' THEN '4'
    END AS Estabelecimento,
    LS.NR_LINHA,
    LS.NM_LINHA,
    L.DT_OPERACAO_LINHA,
    COALESCE(SUM(L.QT_VIAG_PREVISTA_1_3 + L.QT_VIAG_PREVISTA_2), 0) AS "Viagem Programada",
    COALESCE(SUM(L.QT_VIAG_REALIZADA_1_3 + L.QT_VIAG_REALIZADA_2), 0) AS "Viagem Realizada",
    COALESCE((SUM(L.QT_VIAG_REALIZADA_1_3 + L.QT_VIAG_REALIZADA_2) - SUM(L.QT_VIAG_PREVISTA_1_3 + L.QT_VIAG_PREVISTA_2)), 0) AS "Diferença Viagem",
    COALESCE(SUM(L.QT_KM_PREVISTA_1_3 + L.QT_KM_PREVISTA_2), 0) AS "KM Programada",
    COALESCE((SUM(L.QT_KM_PREVISTA_1_3 + L.QT_KM_PREVISTA_2) + L.QT_KM_OCIOSA_PREVISTA), 0) AS "KM Total Programada",
    COALESCE((SUM(L.qt_KM_REALIZADA_1_3 + L.QT_KM_REALIZADA_2) + L.QT_KM_OCIOSA_PREVISTA), 0) AS "KM Realizado TotaL",
    COALESCE(((SUM(L.qt_KM_REALIZADA_1_3 + L.QT_KM_REALIZADA_2) + L.QT_KM_OCIOSA_PREVISTA) - (SUM(L.QT_KM_PREVISTA_1_3 + L.QT_KM_PREVISTA_2) + L.QT_KM_OCIOSA_PREVISTA)), 0) AS "Diferença KM",
    COALESCE(L.QT_KM_OCIOSA_PREVISTA, 0) AS "KM Morta Programada"
FROM 
    grupogem.TA_SINTETICO_OPERACIONAL_LINHA L
INNER JOIN
    grupogem.LINHAS LS ON LS.ID_LINHA = L.ID_LINHA
WHERE 
    LS.ID_EMPRESA IN ('11', '10','009','008','007','004')
    AND L.DT_OPERACAO_LINHA >= TO_DATE('2024-01-01', 'YYYY-MM-DD')
GROUP BY 
    LS.ID_EMPRESA,
    L.ID_LINHA,
    LS.NR_LINHA,
    LS.NM_LINHA,
    L.DT_OPERACAO_LINHA,
    L.QT_KM_OCIOSA_PREVISTA,
    L.QT_KM_OCIOSA
HAVING 
    SUM(L.QT_VIAG_PREVISTA_1_3 + L.QT_VIAG_PREVISTA_2) != 0 
    OR SUM(L.QT_VIAG_REALIZADA_1_3 + L.QT_VIAG_REALIZADA_2) != 0 
    OR SUM(L.QT_KM_PREVISTA_1_3 + L.QT_KM_PREVISTA_2) != 0 
    OR SUM(L.QT_KM_REALIZADA_1_3 + L.QT_KM_REALIZADA_2) != 0 
    OR L.QT_KM_OCIOSA != 0