WITH Consulta AS (
SELECT
    NF.ID_NF_ENTRADA_CABECALHO,
    NF.DT_ENTRADA AS Data,
    EXTRACT(YEAR FROM NF.DT_ENTRADA) AS Ano,
    EXTRACT(MONTH FROM NF.DT_ENTRADA) AS Mes,
    EXTRACT(DAY FROM NF.DT_ENTRADA) AS Dia,
    NF.ID_EMPRESA,
    E.NM_RAZAO_SOCIAL,
    NF.ID_EMPRESA || ' - ' || E.NM_RAZAO_SOCIAL AS Empresa,
    P.CD_PRODUTO AS Codigo_Produto,
    P.NM_PRODUTO AS Produto,
    SG.DS_SUBGRUPO AS Grupo_Item,
    ND.QT_ITEM AS Quantidade_Itens,
    F.CD_FORNECEDOR,
    F.TE_RAZAO_SOCIAL AS Fornecedor,
    TE.DS_TIPO_ENTRADA AS Tipo_Entrada,
    NF.NR_DOCUMENTO AS Numero_NF,
    CASE
        WHEN ROW_NUMBER() OVER (PARTITION BY NF.ID_NF_ENTRADA_CABECALHO ORDER BY NF.ID_NF_ENTRADA_CABECALHO) = 1 THEN 1
        ELSE 0
    END AS ContagemPorDocumento
FROM grupogem.SU_NF_ENTRADAS_DETALHES ND
INNER JOIN 
    grupogem.SU_NF_ENTRADAS_CABECALHOS NF ON NF.ID_NF_ENTRADA_CABECALHO = ND.ID_NF_ENTRADA_CABECALHO
JOIN
    grupogem.SU_TIPOS_ENTRADA TE ON TE.ID_TIPO_ENTRADA = NF.ID_TIPO_ENTRADA
JOIN
    grupogem.SU_PRODUTOS P ON P.ID_PRODUTO = ND.ID_PRODUTO
JOIN
    grupogem.SU_SUBGRUPOS SG ON SG.ID_SUBGRUPO = P.ID_SUBGRUPO
LEFT JOIN
    grupogem.FORNECEDORES F ON F.ID_FORNECEDOR = NF.ID_FORNECEDOR
INNER JOIN
    grupogem.Empresas E ON E.ID_Empresa = NF.ID_Empresa
WHERE
    NF.ID_TIPO_ENTRADA IN ('1', '5')),

B AS (  
SELECT
    C.ID_NF_ENTRADA_CABECALHO,
    C.Data,
    C.Ano,
    C.Mes,
    C.Dia,
    C.Empresa,
    C.Tipo_Entrada,
    C.Numero_NF,
    C.CD_FORNECEDOR,
    C.Fornecedor,
    TO_NUMBER(C.Codigo_Produto) || ' - ' || C.Produto AS Codigo_Nome_Produto,
    COALESCE(NF.VL_TOTAL_NF, 0) AS Valor_Total,
    C.Grupo_Item,
    C.Quantidade_Itens,
    C.ContagemPorDocumento
FROM Consulta C
LEFT JOIN (
    SELECT
    NF.ID_NF_ENTRADA_CABECALHO,
    NF.VL_TOTAL_NF,
    1 AS ContagemPorDocumento
FROM grupogem.SU_NF_ENTRADAS_CABECALHOS NF
WHERE
    NF.ID_TIPO_ENTRADA IN ('1', '5'))NF ON NF.ID_NF_ENTRADA_CABECALHO = C.ID_NF_ENTRADA_CABECALHO AND NF.ContagemPorDocumento = C.ContagemPorDocumento
WHERE 
    C.Data >= TO_DATE('2024-01-01', 'YYYY-MM-DD')
    AND GRUPO_ITEM IN ('CONSULTORIA ADM. E SISTEMA ERP', 'MATERIAL INFORMÁTICA', 'TECNOLOGIA INFORMAÇÃO', 'CERTIFICAÇÃO DIGITAL', 'BILHETAGEM ELETRONICA', 'CURSOS E TREINAMENTOS  - ADM', 'CONSULTORIA ADM. E SISTEMA ERP')
    )
    
SELECT DISTINCT
    DATA AS Data,
    EMPRESA AS Empresa,
    CD_FORNECEDOR AS Codigo_Fornecedor,
    FORNECEDOR AS Fornecedor,
    NUMERO_NF AS Documento,
    CODIGO_NOME_PRODUTO AS Item,
    VALOR_TOTAL AS ValorTotal,
    GRUPO_ITEM AS Item_Grupo_Correto,
    1 AS Quantidade
FROM B