WITH A AS (
    SELECT
        CC.ID_EMPRESA AS Empresa,
        L.DT_LOTE AS Data,
        L.ID_LOTE AS LOTE,
        CL.ID_LOTE,
        L.NM_LOTE,
        CL.ID_LANCAMENTO,
        CL.CS_TIPO,
        CL.ID_CONTA_CONTABIL AS Conta_Contabil,
        CC.ID_CONTA_CONTABIL_PAI AS Pai,
        CASE 
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1%' THEN '1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2%' THEN '2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3%' THEN '3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4%' THEN '4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '5%' THEN '5'
        END AS Nivel_1,
        CASE 
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1%' THEN '1.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2%' THEN '1.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.3%' THEN '1.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.4%' THEN '1.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.5%' THEN '1.5'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.9%' THEN '1.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1%' THEN '2.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2%' THEN '2.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.3%' THEN '2.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.4%' THEN '2.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.9%' THEN '2.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1%' THEN '3.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.2%' THEN '3.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.3%' THEN '3.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.1%' THEN '4.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.2%' THEN '4.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '5.1%' THEN '5.1'
        END AS Nivel_2,
        CASE 
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.1%' THEN '1.1.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.2%' THEN '1.1.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.3%' THEN '1.1.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.4%' THEN '1.1.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.5%' THEN '1.1.5'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.1.6%' THEN '1.1.6'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2.1%' THEN '1.2.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2.2%' THEN '1.2.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2.3%' THEN '1.2.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2.4%' THEN '1.2.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.2.5%' THEN '1.2.5'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.3.1%' THEN '1.3.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.3.2%' THEN '1.3.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.3.3%' THEN '1.3.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.4.1%' THEN '1.4.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.4.2%' THEN '1.4.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.4.3%' THEN '1.4.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1.9.9%' THEN '1.9.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.1%' THEN '2.1.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.2%' THEN '2.1.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.3%' THEN '2.1.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.4%' THEN '2.1.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.5%' THEN '2.1.5'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.6%' THEN '2.1.6'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.1.9%' THEN '2.1.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2.1%' THEN '2.2.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2.2%' THEN '2.2.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2.3%' THEN '2.2.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2.4%' THEN '2.2.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.2.9%' THEN '2.2.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.3.1%' THEN '2.3.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.3.2%' THEN '2.3.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.3.3%' THEN '2.3.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.4.1%' THEN '2.4.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.4.2%' THEN '2.4.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.4.3%' THEN '2.4.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.4.4%' THEN '2.4.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2.9.9%' THEN '2.9.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.1%' THEN '3.1.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.2%' THEN '3.1.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.3%' THEN '3.1.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.4%' THEN '3.1.4'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.5%' THEN '3.1.5'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.6%' THEN '3.1.6'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.1.9%' THEN '3.1.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.2.1%' THEN '3.2.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.2.2%' THEN '3.2.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.2.3%' THEN '3.2.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.2.9%' THEN '3.2.9'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.3.1%' THEN '3.3.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.3.2%' THEN '3.3.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.3.3%' THEN '3.3.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.4.1%' THEN '3.4.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.4.2%' THEN '3.4.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.4.3%' THEN '3.4.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3.4.4%' THEN '3.4.4' 
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.1.1%' THEN '4.1.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.1.2%' THEN '4.1.2'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.1.3%' THEN '4.1.3'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.2.1%' THEN '4.2.1'
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4.2.2%' THEN '4.2.2'  
            WHEN CC.NR_CONTA_CONTABIL_FORMATADO LIKE '5.1.1%' THEN '5.1.1'
        END AS Nivel_3,
        SUM(CASE WHEN CL.CS_TIPO = 'D' THEN -VL_LANCAMENTO ELSE 0 END) AS Debito,
        SUM(CASE WHEN CL.CS_TIPO = 'C' THEN VL_LANCAMENTO ELSE 0 END) AS Credito,
        CC.NR_CONTA_CONTABIL_FORMATADO AS Nivel_5
    FROM 
        grupogem.CO_LANCAMENTOS CL
    LEFT JOIN
        grupogem.CONTAS_CONTABEIS CC ON CC.ID_CONTA_CONTABIL = CL.ID_CONTA_CONTABIL
    LEFT JOIN
        grupogem.CO_LOTES L ON L.ID_LOTE = CL.ID_LOTE
    WHERE
        CC.NR_CONTA_CONTABIL_FORMATADO LIKE '1%' 
        OR CC.NR_CONTA_CONTABIL_FORMATADO LIKE '2%'
        OR CC.NR_CONTA_CONTABIL_FORMATADO LIKE '3%'
        OR CC.NR_CONTA_CONTABIL_FORMATADO LIKE '4%'
    GROUP BY
        CC.ID_EMPRESA,
        L.ID_LOTE,
        L.NM_LOTE,
        L.DT_LOTE,
        CL.CS_TIPO,
        CL.ID_LOTE,
        CL.ID_LANCAMENTO,
        CL.ID_CONTA_CONTABIL,
        CC.ID_CONTA_CONTABIL_PAI,
        CC.NR_CONTA_CONTABIL_FORMATADO
)

SELECT
    A.Empresa,
    A.Data,
    E.NM_Empresa,
    EXTRACT(MONTH FROM A.Data) AS Mes,
    CASE
        WHEN EXTRACT(MONTH FROM A.Data) = 1 THEN 'JANEIRO'
        WHEN EXTRACT(MONTH FROM A.Data) = 2 THEN 'FEVEREIRO'
        WHEN EXTRACT(MONTH FROM A.Data) = 3 THEN 'MARÇO'
        WHEN EXTRACT(MONTH FROM A.Data) = 4 THEN 'ABRIL'
        WHEN EXTRACT(MONTH FROM A.Data) = 5 THEN 'MAIO'
        WHEN EXTRACT(MONTH FROM A.Data) = 6 THEN 'JUNHO'
        WHEN EXTRACT(MONTH FROM A.Data) = 7 THEN 'JULHO'
        WHEN EXTRACT(MONTH FROM A.Data) = 8 THEN 'AGOSTO'
        WHEN EXTRACT(MONTH FROM A.Data) = 9 THEN 'SETEMBRO'
        WHEN EXTRACT(MONTH FROM A.Data) = 10 THEN 'OUTUBRO'
        WHEN EXTRACT(MONTH FROM A.Data) = 11 THEN 'NOVEMBRO'
        WHEN EXTRACT(MONTH FROM A.Data) = 12 THEN 'DEZEMBRO'
    END AS Nome_Mes,
    A.Nivel_1 || ' - ' || CC.DS_CONTA_CONTABIL AS Nivel_1,
    A.Nivel_2 || ' - ' || DD.DS_CONTA_CONTABIL AS Nivel_2,
    A.Nivel_3 || ' - ' || EE.DS_CONTA_CONTABIL AS Nivel_3,
    A.Nivel_5 || ' - ' || GG.DS_CONTA_CONTABIL AS Nivel_5,
    A.Debito,
    A.Nivel_1,
    A.Nivel_2,
    A.Nivel_3,
    A.Nivel_5,
    A.CS_tipo,
    A.Credito
FROM
    A
LEFT JOIN
    grupogem.contas_contabeis CC ON CC.NR_CONTA_CONTABIL_FORMATADO = A.Nivel_1 AND CC.ID_Empresa = A.Empresa
LEFT JOIN
    grupogem.contas_contabeis DD ON DD.NR_CONTA_CONTABIL_FORMATADO = A.Nivel_2 AND DD.ID_Empresa = A.Empresa
LEFT JOIN
    grupogem.contas_contabeis EE ON EE.NR_CONTA_CONTABIL_FORMATADO = A.Nivel_3 AND EE.ID_Empresa = A.Empresa
LEFT JOIN
    grupogem.contas_contabeis GG ON GG.NR_CONTA_CONTABIL_FORMATADO = A.Nivel_5 AND GG.ID_Empresa = A.Empresa
LEFT JOIN
    grupogem.Empresas E ON E.ID_Empresa = A.Empresa
WHERE
    A.NM_LOTE != 'ENCERRAMENTO'

